services:
  reverse-proxy:
    image: nginx:1.17.10
    container_name: reverse_proxy_demo
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  backend:
    image:  ghcr.io/integratedproject-int221/back-end:master
    container_name: backend
    ports:
      - '3000:3000'
    restart: on-failure    
  frontend:
    build: front-end
    container_name: frontend
    depends_on:
      - backend
    restart: on-failure

